name: Test Recall Local

on:
  issues:
    types: [assigned]

env:
  GITHUB_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}

jobs:
  test-call:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/branch-action.yml
    #secrets: inherit